version: "3"

services:
  web:
    image: posox/brbl-stats-api:latest
    networks:
      - backend
      - frontend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db/postgres"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    ports:
      - "8000:8000"
  engine:
    image: posox/brbl-stats-engine:latest
    networks:
      - backend
    environment:
      DATABASE_URL: "postgres://postgres:password@db/postgres"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  init-db:
    image: posox/brbl-stats-engine:latest
    networks:
      - backend
    environment:
      DATABASE_URL: "postgres://postgres:password@db/postgres"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: python -m brbl_stats.dbutils
  db:
    image: postgres:11
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:
